/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author ssoar
 */
public class PaginaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form paginaPrincipal
     */
    public PaginaPrincipal() {
        initComponents();
    }
    
    private void terminar() {        
      UIManager.put("OptionPane.noButtonText", "Não");  
      UIManager.put("OptionPane.yesButtonText", "Sim");

       if (JOptionPane.showConfirmDialog(null, 
              "Deseja realmente terminar o programa?", 
              "Terminar",

              JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
               dispose();
               System.exit(0);

      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbDepthfirst = new javax.swing.JRadioButton();
        rbIterativeDeepening = new javax.swing.JRadioButton();
        rbBreadthfirst = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        btTerminar = new javax.swing.JLabel();
        btProximo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setUndecorated(true);
        getContentPane().setLayout(null);

        buttonGroup1.add(rbDepthfirst);
        rbDepthfirst.setFont(new java.awt.Font("Arial Nova Light", 0, 12)); // NOI18N
        rbDepthfirst.setText("Depthfirst");
        rbDepthfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDepthfirstActionPerformed(evt);
            }
        });
        getContentPane().add(rbDepthfirst);
        rbDepthfirst.setBounds(150, 110, 93, 25);

        buttonGroup1.add(rbIterativeDeepening);
        rbIterativeDeepening.setFont(new java.awt.Font("Arial Nova Light", 0, 12)); // NOI18N
        rbIterativeDeepening.setText("Iterativedeepening");
        getContentPane().add(rbIterativeDeepening);
        rbIterativeDeepening.setBounds(150, 150, 150, 25);

        buttonGroup1.add(rbBreadthfirst);
        rbBreadthfirst.setFont(new java.awt.Font("Arial Nova Light", 0, 12)); // NOI18N
        rbBreadthfirst.setText("Breadthfirst");
        getContentPane().add(rbBreadthfirst);
        rbBreadthfirst.setBounds(150, 190, 93, 25);

        jLabel1.setFont(new java.awt.Font("Arial Nova Light", 1, 12)); // NOI18N
        jLabel1.setText("Qual o método de pesquisa pretende usar ?");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 60, 270, 30);

        btTerminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/sair.png"))); // NOI18N
        btTerminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btTerminarMouseClicked(evt);
            }
        });
        getContentPane().add(btTerminar);
        btTerminar.setBounds(30, 240, 80, 30);

        btProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/right-arrow (2).png"))); // NOI18N
        btProximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btProximoMouseClicked(evt);
            }
        });
        getContentPane().add(btProximo);
        btProximo.setBounds(330, 240, 70, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbDepthfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDepthfirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDepthfirstActionPerformed

    private void btProximoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProximoMouseClicked
        // TODO add your handling code here:
        if (rbDepthfirst.isSelected()) {
            String Method = "depthfirst";
        
            dispose();
            Caminho caminho = new Caminho(Method);
            caminho.setLocationRelativeTo(null);
            caminho.setVisible(true);
        
        } else if (rbIterativeDeepening.isSelected()) {
            String Method = "iterativedeepening";
        
            dispose();
            Caminho caminho = new Caminho(Method);
            caminho.setLocationRelativeTo(null);
            caminho.setVisible(true);
        
        } else if (rbBreadthfirst.isSelected()) {
            String Method = "breadthfirst";
        
            dispose();
            Caminho caminho = new Caminho(Method);
            caminho.setLocationRelativeTo(null);
            caminho.setVisible(true);
        
        } else {
         JOptionPane.showMessageDialog(null,"Selecione uma das alternativas","Erro",JOptionPane.ERROR_MESSAGE);
     }    
    }//GEN-LAST:event_btProximoMouseClicked

    private void btTerminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTerminarMouseClicked
        // TODO add your handling code here:
        terminar();
    }//GEN-LAST:event_btTerminarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btProximo;
    private javax.swing.JLabel btTerminar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbBreadthfirst;
    private javax.swing.JRadioButton rbDepthfirst;
    private javax.swing.JRadioButton rbIterativeDeepening;
    // End of variables declaration//GEN-END:variables
}
