/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author ssoar
 */
public class Regiao extends javax.swing.JFrame {

    /**
     * Creates new form região
     */
    public Regiao() {
        initComponents();
    }
    
    private void terminar() {        
      UIManager.put("OptionPane.noButtonText", "Não");  
      UIManager.put("OptionPane.yesButtonText", "Sim");

       if (JOptionPane.showConfirmDialog(null, 
              "Deseja realmente terminar o programa?", 
              "Terminar",

              JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
               dispose();
               System.exit(0);

      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbNorte = new javax.swing.JRadioButton();
        rbCentro = new javax.swing.JRadioButton();
        rbSul = new javax.swing.JRadioButton();
        rbIlhas = new javax.swing.JRadioButton();
        btProximo = new javax.swing.JLabel();
        btSair = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(616, 409));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Nova Light", 1, 14)); // NOI18N
        jLabel1.setText("Qual a sua região ?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 110, 140, 19);

        buttonGroup1.add(rbNorte);
        rbNorte.setFont(new java.awt.Font("Arial Nova Light", 0, 12)); // NOI18N
        rbNorte.setText("Norte");
        getContentPane().add(rbNorte);
        rbNorte.setBounds(280, 140, 60, 25);

        buttonGroup1.add(rbCentro);
        rbCentro.setFont(new java.awt.Font("Arial Nova Light", 0, 12)); // NOI18N
        rbCentro.setText("Centro");
        getContentPane().add(rbCentro);
        rbCentro.setBounds(280, 180, 70, 25);

        buttonGroup1.add(rbSul);
        rbSul.setFont(new java.awt.Font("Arial Nova Light", 0, 12)); // NOI18N
        rbSul.setText("Sul");
        getContentPane().add(rbSul);
        rbSul.setBounds(280, 220, 60, 25);

        buttonGroup1.add(rbIlhas);
        rbIlhas.setFont(new java.awt.Font("Arial Nova Light", 0, 12)); // NOI18N
        rbIlhas.setText("Ilhas");
        getContentPane().add(rbIlhas);
        rbIlhas.setBounds(280, 260, 60, 25);

        btProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/right-arrow (2).png"))); // NOI18N
        btProximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btProximoMouseClicked(evt);
            }
        });
        getContentPane().add(btProximo);
        btProximo.setBounds(550, 190, 40, 32);

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        btSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSairMouseClicked(evt);
            }
        });
        getContentPane().add(btSair);
        btSair.setBounds(20, 190, 40, 32);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo_5.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-5, -6, 630, 417);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btProximoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProximoMouseClicked
        // TODO add your handling code here:
          if (rbNorte.isSelected() || rbCentro.isSelected() || rbSul.isSelected() || rbIlhas.isSelected())
        {
            dispose();
            Pergunta1 pergunta1 = new Pergunta1();
            pergunta1.setLocationRelativeTo(null);
            pergunta1.setVisible(true);            
        }
        
        else {
            JOptionPane.showMessageDialog(null,"Selecione uma das alternativas","Atenção",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btProximoMouseClicked

    private void btSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairMouseClicked
        // TODO add your handling code here:
        terminar();
    }//GEN-LAST:event_btSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main1(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Regiao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Regiao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Regiao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Regiao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Regiao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btProximo;
    private javax.swing.JLabel btSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rbCentro;
    private javax.swing.JRadioButton rbIlhas;
    private javax.swing.JRadioButton rbNorte;
    private javax.swing.JRadioButton rbSul;
    // End of variables declaration//GEN-END:variables
}
