/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author ssoar
 */
public class Pergunta2 extends javax.swing.JFrame {

    /**
     * Creates new form pergunta_2
     */
    private String mensagem;
    
    public Pergunta2(String mensagem) {
        initComponents();
        this.mensagem = mensagem;
    }
    
     private void terminar() {        
       UIManager.put("OptionPane.noButtonText", "Não");  
       UIManager.put("OptionPane.yesButtonText", "Sim");
        
        if (JOptionPane.showConfirmDialog(null, 
               "Deseja realmente terminar o programa?", 
               "Terminar",
               
               JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                dispose();
                System.exit(0);
            
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        btSair = new javax.swing.JLabel();
        btProximo = new javax.swing.JLabel();
        cbFastFood = new javax.swing.JCheckBox();
        cbVegetariana = new javax.swing.JCheckBox();
        cbComidaTradicional = new javax.swing.JCheckBox();
        cbComidaOriental = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(616, 409));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Nova Light", 1, 14)); // NOI18N
        jLabel2.setText("Que tipo de refeição consome mais frequentemente ?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 140, 390, 23);

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        btSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSairMouseClicked(evt);
            }
        });
        getContentPane().add(btSair);
        btSair.setBounds(20, 190, 40, 32);

        btProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/right-arrow (2).png"))); // NOI18N
        btProximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btProximoMouseClicked(evt);
            }
        });
        getContentPane().add(btProximo);
        btProximo.setBounds(550, 190, 40, 32);

        cbFastFood.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbFastFood.setText("Fast-Food");
        cbFastFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFastFoodActionPerformed(evt);
            }
        });
        getContentPane().add(cbFastFood);
        cbFastFood.setBounds(270, 180, 81, 23);

        cbVegetariana.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbVegetariana.setText("Vegetariana");
        getContentPane().add(cbVegetariana);
        cbVegetariana.setBounds(270, 210, 93, 23);

        cbComidaTradicional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbComidaTradicional.setText("Comida Tradicional");
        cbComidaTradicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbComidaTradicionalActionPerformed(evt);
            }
        });
        getContentPane().add(cbComidaTradicional);
        cbComidaTradicional.setBounds(270, 240, 133, 23);

        cbComidaOriental.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbComidaOriental.setText("Comida Oriental");
        cbComidaOriental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbComidaOrientalActionPerformed(evt);
            }
        });
        getContentPane().add(cbComidaOriental);
        cbComidaOriental.setBounds(270, 270, 115, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo_5.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 630, 420);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbComidaTradicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbComidaTradicionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbComidaTradicionalActionPerformed

    private void cbComidaOrientalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbComidaOrientalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbComidaOrientalActionPerformed

    private void cbFastFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFastFoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFastFoodActionPerformed

    private void btProximoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProximoMouseClicked
        // TODO add your handling code here:
   
        
        if (cbFastFood.isSelected() || cbVegetariana.isSelected() || cbComidaTradicional.isSelected() || cbComidaOriental.isSelected()){
             if (cbFastFood.isSelected()){
                 String tipo = "'fastFood'";
                 mensagem += "assert(fact("+tipo+")),";
                 
                 System.out.println(mensagem);
                 
                 this.dispose();
                 Pergunta3 pergunta3 = new Pergunta3(mensagem);
                 pergunta3.setLocationRelativeTo(null);
                 pergunta3.setVisible(true);
                 
              
             }
              if (cbVegetariana.isSelected()){
                 String tipo = "'vegetariana'";
                 mensagem += "assert(fact("+tipo+")),";
                 
                 System.out.println(mensagem);
                 
                 this.dispose();
                 Pergunta3 pergunta3 = new Pergunta3(mensagem);
                 pergunta3.setLocationRelativeTo(null);
                 pergunta3.setVisible(true);
                 
             }
               if (cbComidaTradicional.isSelected()){
                 String tipo = "'comidaTradicional'";
                 mensagem += "assert(fact("+tipo+")),";
                 
                 System.out.println(mensagem);
                 
                 this.dispose();
                 Pergunta3 pergunta3 = new Pergunta3(mensagem);
                 pergunta3.setLocationRelativeTo(null);
                 pergunta3.setVisible(true);
                 
             }
               if (cbComidaOriental.isSelected()){
                 String tipo = "'comidaOriental'";
                 mensagem += "assert(fact("+tipo+")),";
                 
                 System.out.println(mensagem);
                 
                 this.dispose();
                 Pergunta3 pergunta3 = new Pergunta3(mensagem);
                 pergunta3.setLocationRelativeTo(null);
                 pergunta3.setVisible(true);
                 
             }
        }
        
        else {
                JOptionPane.showMessageDialog(null,"Selecione uma das alternativas","Erro",JOptionPane.ERROR_MESSAGE);
     }
    }//GEN-LAST:event_btProximoMouseClicked

    private void btSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairMouseClicked
        // TODO add your handling code here:
        terminar();
    }//GEN-LAST:event_btSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main1(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Pergunta2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btProximo;
    private javax.swing.JLabel btSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbComidaOriental;
    private javax.swing.JCheckBox cbComidaTradicional;
    private javax.swing.JCheckBox cbFastFood;
    private javax.swing.JCheckBox cbVegetariana;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
