/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author ssoar
 */
public class Pergunta1 extends javax.swing.JFrame {

    /**
     * Creates new form pergunta_1
     */
    public Pergunta1() {
        initComponents();
    }
    
    private void terminar() {        
      UIManager.put("OptionPane.noButtonText", "Não");  
      UIManager.put("OptionPane.yesButtonText", "Sim");

       if (JOptionPane.showConfirmDialog(null, 
              "Deseja realmente terminar o programa?", 
              "Terminar",

              JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
               dispose();
               System.exit(0);

      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        rbNormal = new javax.swing.JRadioButton();
        rbVegetariano = new javax.swing.JRadioButton();
        rbVegan = new javax.swing.JRadioButton();
        btProximo = new javax.swing.JLabel();
        btSair = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(616, 409));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Nova Light", 1, 14)); // NOI18N
        jLabel2.setText("Qual o seu estilo alimentar ?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 130, 250, 20);

        rbNormal.setFont(new java.awt.Font("Arial Nova Light", 0, 12)); // NOI18N
        rbNormal.setText("Normal");
        rbNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNormalActionPerformed(evt);
            }
        });
        getContentPane().add(rbNormal);
        rbNormal.setBounds(280, 170, 90, 25);

        rbVegetariano.setFont(new java.awt.Font("Arial Nova Light", 0, 12)); // NOI18N
        rbVegetariano.setText("Vegetariano");
        getContentPane().add(rbVegetariano);
        rbVegetariano.setBounds(280, 210, 100, 25);

        rbVegan.setFont(new java.awt.Font("Arial Nova Light", 0, 12)); // NOI18N
        rbVegan.setText("Vegan");
        rbVegan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVeganActionPerformed(evt);
            }
        });
        getContentPane().add(rbVegan);
        rbVegan.setBounds(280, 250, 70, 25);

        btProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/right-arrow (2).png"))); // NOI18N
        btProximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btProximoMouseClicked(evt);
            }
        });
        getContentPane().add(btProximo);
        btProximo.setBounds(540, 190, 40, 32);

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        btSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSairMouseClicked(evt);
            }
        });
        getContentPane().add(btSair);
        btSair.setBounds(20, 190, 40, 32);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo_5.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 640, 430);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNormalActionPerformed

    private void btProximoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProximoMouseClicked
        // TODO add your handling code here:
        String mensagem = "";
     
     if (rbNormal.isSelected()) {
         String regime = "'normal'";
         mensagem = "assert(fact("+regime+")),";
         
        System.out.println(mensagem);
        
        dispose();
        Pergunta2 pergunta2 = new Pergunta2(mensagem);
        pergunta2.setLocationRelativeTo(null);
        pergunta2.setVisible(true);
    
     } else if (rbVegetariano.isSelected()) {
        String regime = "'vegetariano'";
        mensagem = "assert(fact("+regime+")),";
         
        System.out.println(mensagem);
        
        dispose();
        Pergunta2 pergunta2 = new Pergunta2(mensagem);
        pergunta2.setLocationRelativeTo(null);
        pergunta2.setVisible(true);
         
     } else if (rbVegan.isSelected()) {
        String regime = "'vegan'";
        mensagem = "assert(fact("+regime+")),";
         
        System.out.println(mensagem);
        
        dispose();
        Pergunta2 pergunta2 = new Pergunta2(mensagem);
        pergunta2.setLocationRelativeTo(null);
        pergunta2.setVisible(true);        
     }
     
     else {
         JOptionPane.showMessageDialog(null,"Selecione uma das alternativas","Erro",JOptionPane.ERROR_MESSAGE);
     }
        
    }//GEN-LAST:event_btProximoMouseClicked

    private void rbVeganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVeganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbVeganActionPerformed

    private void btSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairMouseClicked
        // TODO add your handling code here:
        terminar();
    }//GEN-LAST:event_btSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main1(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pergunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pergunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pergunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pergunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Pergunta1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btProximo;
    private javax.swing.JLabel btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rbNormal;
    private javax.swing.JRadioButton rbVegan;
    private javax.swing.JRadioButton rbVegetariano;
    // End of variables declaration//GEN-END:variables
}
