/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author ssoar
 */
public class Pergunta3 extends javax.swing.JFrame {

    /**
     * Creates new form pergunta_3
     */
    private String mensagem;
    
    public Pergunta3(String mensagem) {
        initComponents();
        this.mensagem = mensagem;
    }
    
     private void terminar() {        
       UIManager.put("OptionPane.noButtonText", "Não");  
       UIManager.put("OptionPane.yesButtonText", "Sim");
        
        if (JOptionPane.showConfirmDialog(null, 
               "Deseja realmente terminar o programa?", 
               "Terminar",
               
               JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                dispose();
                System.exit(0);
            
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        rbUmDez = new javax.swing.JRadioButton();
        rbVinteMais = new javax.swing.JRadioButton();
        rbOnzeVinte = new javax.swing.JRadioButton();
        btProximo = new javax.swing.JLabel();
        btSair = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(616, 409));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Nova Light", 1, 14)); // NOI18N
        jLabel2.setText("Qual o valor máximo que está disposto a pagar por uma refeição ?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 160, 480, 20);

        buttonGroup1.add(rbUmDez);
        rbUmDez.setFont(new java.awt.Font("Arial Nova Light", 0, 12)); // NOI18N
        rbUmDez.setText("1-10");
        getContentPane().add(rbUmDez);
        rbUmDez.setBounds(280, 190, 60, 25);

        buttonGroup1.add(rbVinteMais);
        rbVinteMais.setFont(new java.awt.Font("Arial Nova Light", 0, 12)); // NOI18N
        rbVinteMais.setText("20+");
        getContentPane().add(rbVinteMais);
        rbVinteMais.setBounds(280, 270, 70, 25);

        buttonGroup1.add(rbOnzeVinte);
        rbOnzeVinte.setFont(new java.awt.Font("Arial Nova Light", 0, 12)); // NOI18N
        rbOnzeVinte.setText("11-20");
        rbOnzeVinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOnzeVinteActionPerformed(evt);
            }
        });
        getContentPane().add(rbOnzeVinte);
        rbOnzeVinte.setBounds(280, 230, 70, 25);

        btProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/right-arrow (2).png"))); // NOI18N
        btProximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btProximoMouseClicked(evt);
            }
        });
        getContentPane().add(btProximo);
        btProximo.setBounds(550, 190, 40, 32);

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        btSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSairMouseClicked(evt);
            }
        });
        getContentPane().add(btSair);
        btSair.setBounds(20, 190, 40, 32);

        jLabel1.setFont(new java.awt.Font("Arial Nova Light", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo_5.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-5, -6, 630, 430);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbOnzeVinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOnzeVinteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbOnzeVinteActionPerformed

    private void btProximoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProximoMouseClicked
        // TODO add your handling code here: 
     if (rbUmDez.isSelected()) {
         String preco = "'1-10'";
         mensagem += "assert(fact("+ preco +")),";
         
        System.out.println(mensagem);
        
        dispose();
        Pergunta4 pergunta4 = new Pergunta4(mensagem);
        pergunta4.setLocationRelativeTo(null);
        pergunta4.setVisible(true);
    
     } else if (rbOnzeVinte.isSelected()) {
        String preco = "'11-20'";
        mensagem += "assert(fact("+ preco +")),";
         
        System.out.println(mensagem);
        
         dispose();
        Pergunta4 pergunta4 = new Pergunta4(mensagem);
        pergunta4.setLocationRelativeTo(null);
        pergunta4.setVisible(true);
         
     } else if (rbVinteMais.isSelected()) {
        String preco = "'20+'";
        mensagem += "assert(fact("+ preco +")),";
         
        System.out.println(mensagem);
        
        dispose();
        Pergunta4 pergunta4 = new Pergunta4(mensagem);
        pergunta4.setLocationRelativeTo(null);
        pergunta4.setVisible(true);        
     }
     
     else {
         JOptionPane.showMessageDialog(null,"Selecione uma das alternativas","Erro",JOptionPane.ERROR_MESSAGE);
     }
    }//GEN-LAST:event_btProximoMouseClicked

    private void btSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairMouseClicked
        // TODO add your handling code here:
        terminar();
    }//GEN-LAST:event_btSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main1(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pergunta3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pergunta3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pergunta3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pergunta3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Pergunta3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btProximo;
    private javax.swing.JLabel btSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rbOnzeVinte;
    private javax.swing.JRadioButton rbUmDez;
    private javax.swing.JRadioButton rbVinteMais;
    // End of variables declaration//GEN-END:variables
}
