/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Rodrigo
 */
public class PerguntaRestricao extends javax.swing.JFrame {

    /**
     * Creates new form PerguntaRestricao
     */
    
    private String mensagem;
    
    public PerguntaRestricao(String mensagem) {
        initComponents();
        this.mensagem = mensagem;
    }
    
     private void terminar() {        
      UIManager.put("OptionPane.noButtonText", "Não");  
      UIManager.put("OptionPane.yesButtonText", "Sim");

       if (JOptionPane.showConfirmDialog(null, 
              "Deseja realmente terminar o programa?", 
              "Terminar",

              JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
               dispose();
               System.exit(0);

      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        rbGluten = new javax.swing.JRadioButton();
        rbLactose = new javax.swing.JRadioButton();
        btProximo = new javax.swing.JLabel();
        btSair = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(616, 408));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Nova Light", 1, 14)); // NOI18N
        jLabel2.setText("Qual os seguintes compostos o afeta ?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 130, 270, 40);

        buttonGroup1.add(rbGluten);
        rbGluten.setFont(new java.awt.Font("Arial Nova Light", 0, 12)); // NOI18N
        rbGluten.setText("Glúten");
        getContentPane().add(rbGluten);
        rbGluten.setBounds(280, 180, 100, 23);

        buttonGroup1.add(rbLactose);
        rbLactose.setFont(new java.awt.Font("Arial Nova Light", 0, 12)); // NOI18N
        rbLactose.setText("Lactose");
        getContentPane().add(rbLactose);
        rbLactose.setBounds(280, 230, 93, 23);

        btProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/right-arrow (2).png"))); // NOI18N
        btProximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btProximoMouseClicked(evt);
            }
        });
        getContentPane().add(btProximo);
        btProximo.setBounds(570, 190, 50, 40);

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        btSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSairMouseClicked(evt);
            }
        });
        getContentPane().add(btSair);
        btSair.setBounds(10, 200, 40, 30);

        jLabel1.setFont(new java.awt.Font("Arial Nova Light", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo_5.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -10, 630, 430);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairMouseClicked
        // TODO add your handling code here:
        terminar();
    }//GEN-LAST:event_btSairMouseClicked

    private void btProximoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProximoMouseClicked
        // TODO add your handling code here:
     
     if (rbGluten.isSelected()) {
         String restricao = "'noGluten'";
         mensagem += "assert(fact("+restricao+")),";
         
        System.out.println(mensagem);
        
        dispose();
        PerguntaRestricao3 pergunta3 = new PerguntaRestricao3(mensagem);
        pergunta3.setLocationRelativeTo(null);
        pergunta3.setVisible(true);
    
     } else if (rbLactose.isSelected()) {
        String restricao = "'noLactose'";
        mensagem += "assert(fact("+restricao+")),";
         
        System.out.println(mensagem);
        
        dispose();
        PerguntaRestricao3 pergunta3 = new PerguntaRestricao3(mensagem);
        pergunta3.setLocationRelativeTo(null);
        pergunta3.setVisible(true);      
     
     } else {
         JOptionPane.showMessageDialog(null,"Selecione uma das alternativas","Erro",JOptionPane.ERROR_MESSAGE);
     }
    }//GEN-LAST:event_btProximoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main1(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerguntaRestricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerguntaRestricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerguntaRestricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerguntaRestricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PerguntaRestricao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btProximo;
    private javax.swing.JLabel btSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rbGluten;
    private javax.swing.JRadioButton rbLactose;
    // End of variables declaration//GEN-END:variables
}
