/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.jpl7.Query;

/**
 *
 * @author ssoar
 */
public class Pergunta5 extends javax.swing.JFrame {

    /**
     * Creates new form pergunta_4
     */
    private String mensagem;
    
    public Pergunta5(String mensagem) {
        initComponents();
        
        this.mensagem = mensagem;
    }
    
     private void terminar() {        
       UIManager.put("OptionPane.noButtonText", "Não");  
       UIManager.put("OptionPane.yesButtonText", "Sim");
        
        if (JOptionPane.showConfirmDialog(null, 
               "Deseja realmente terminar o programa?", 
               "Terminar",
               
               JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                dispose();
                System.exit(0);
            
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        btProximo = new javax.swing.JLabel();
        btSair = new javax.swing.JLabel();
        rbDiasEspeciais = new javax.swing.JRadioButton();
        rbAlgumasVezes = new javax.swing.JRadioButton();
        rbDieta = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(616, 409));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Nova Light", 1, 14)); // NOI18N
        jLabel3.setText("Em que circunstâncias costuma encomendar comida ?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 140, 380, 19);

        btProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/right-arrow (2).png"))); // NOI18N
        btProximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btProximoMouseClicked(evt);
            }
        });
        getContentPane().add(btProximo);
        btProximo.setBounds(550, 190, 40, 32);

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        btSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSairMouseClicked(evt);
            }
        });
        getContentPane().add(btSair);
        btSair.setBounds(20, 190, 40, 32);

        buttonGroup1.add(rbDiasEspeciais);
        rbDiasEspeciais.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbDiasEspeciais.setText("Dias Especiais");
        getContentPane().add(rbDiasEspeciais);
        rbDiasEspeciais.setBounds(270, 180, 120, 23);

        buttonGroup1.add(rbAlgumasVezes);
        rbAlgumasVezes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbAlgumasVezes.setText("Algumas Vezes");
        getContentPane().add(rbAlgumasVezes);
        rbAlgumasVezes.setBounds(270, 220, 120, 23);

        buttonGroup1.add(rbDieta);
        rbDieta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbDieta.setText("Dieta");
        rbDieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDietaActionPerformed(evt);
            }
        });
        getContentPane().add(rbDieta);
        rbDieta.setBounds(270, 260, 100, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo_5.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-10, -10, 640, 440);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btProximoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProximoMouseClicked
        // TODO add your handling code here:
        //String con = "consult('./base_conhecimento.pl')";
        Query query = new Query("consult('C:/Users/Rodrigo/Desktop/Universidade/2º semestre/SBC/SBC_Parte11/base_conhecimento.pl')");
        
   
        System.out.println("consult " + (query.hasSolution() ? "ok" : "falhou"));
        
        if (rbDiasEspeciais.isSelected() || rbAlgumasVezes.isSelected() || rbDieta.isSelected()){
            if (rbDiasEspeciais.isSelected()){
                 String ocasiao = "'diasEspeciais'";
                 mensagem += "assert(fact("+ ocasiao +")),resposta(P).";                 
                 
                System.out.println(mensagem);
                 
                Query result = new Query(mensagem);   
      
                String refeicao =  result.oneSolution().get("P").toString();
                              
                refeicao = refeicao.replace("â‚¬", " €");
                refeicao = refeicao.replace("Ã§Ã£", "çã");
                refeicao = refeicao.replace("[[['  ", "");  
                refeicao = refeicao.replace("[[['", "");
                refeicao = refeicao.replace("']], _1]", ""); 

                if(refeicao.length() != 0) {
                     try {
                         dispose();
                         Resultado resultado = new Resultado(refeicao);
                         resultado.setLocationRelativeTo(null);
                         resultado.setVisible(true);
                     } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null,"Ocorreu um erro","Erro",JOptionPane.ERROR_MESSAGE);
                     }
                
                } else {                  
                    JOptionPane.showMessageDialog(null, "Nenhum resultado encontrado.","Informação",JOptionPane.INFORMATION_MESSAGE);
                }
        
                System.out.println(refeicao); 
                
             }
             
            if (rbAlgumasVezes.isSelected()){
                String ocasiao = "'algumasVezes'";
                this.mensagem += "assert(fact("+ ocasiao +")),resposta(P).";                 

                System.out.println(mensagem);

                Query result = new Query(mensagem);   

                String refeicao =  result.oneSolution().get("P").toString();

                refeicao = refeicao.replace("â‚¬", " €");
                refeicao = refeicao.replace("Ã§Ã£", "çã");
                refeicao = refeicao.replace("[[['  ", "");  
                refeicao = refeicao.replace("[[['", "");
                refeicao = refeicao.replace("']], _1]", ""); 

                if(refeicao.length() != 0) {
                    try {
                        dispose();
                        Resultado resultado = new Resultado(refeicao);
                        resultado.setLocationRelativeTo(null);   
                        resultado.setVisible(true);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null,"Ocorreu um erro","Erro",JOptionPane.ERROR_MESSAGE);
                    }

                } else {                  
                    JOptionPane.showMessageDialog(null, "Nenhum resultado encontrado.","Informação",JOptionPane.INFORMATION_MESSAGE);
                }

                System.out.println(refeicao);  
                
             }
            if (rbDieta.isSelected()){
                String ocasiao = "'dieta'";
                mensagem += "assert(fact("+ ocasiao +")),resposta(P).";                 

                System.out.println(mensagem);

                Query result = new Query(mensagem);   

                String refeicao =  result.oneSolution().get("P").toString();

                refeicao = refeicao.replace("â‚¬", " €");
                refeicao = refeicao.replace("Ã§Ã£", "çã");
                refeicao = refeicao.replace("[[['  ", ""); 
                refeicao = refeicao.replace("[[['", "");
                refeicao = refeicao.replace("']], _1]", ""); 

                    if(refeicao.length() != 0) {
                    try {
                        dispose();
                        Resultado resultado = new Resultado(refeicao);
                        resultado.setLocationRelativeTo(null);                   
                        resultado.setVisible(true);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null,"Ocorreu um erro","Erro",JOptionPane.ERROR_MESSAGE);
                    }
                     
                    } else {                  
                        JOptionPane.showMessageDialog(null, "Nenhum resultado encontrado.","Informação",JOptionPane.INFORMATION_MESSAGE);
                    }
                    
                    System.out.println(refeicao);  
                    
                }
        } else { 
                    JOptionPane.showMessageDialog(null,"Selecione pelo menos uma das alternativas","Erro",JOptionPane.ERROR_MESSAGE);
               }
       
    }//GEN-LAST:event_btProximoMouseClicked

    private void btSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairMouseClicked
        // TODO add your handling code here:
        terminar();
    }//GEN-LAST:event_btSairMouseClicked

    private void rbDietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDietaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDietaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main1(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pergunta5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pergunta5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pergunta5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pergunta5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Pergunta5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btProximo;
    private javax.swing.JLabel btSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbAlgumasVezes;
    private javax.swing.JRadioButton rbDiasEspeciais;
    private javax.swing.JRadioButton rbDieta;
    // End of variables declaration//GEN-END:variables
}
