/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Rodrigo
 */

public class Resultado extends javax.swing.JFrame {
    
    private String mensagem;

    /**
     * Creates new form Teste
     * @param mensagem
     * @throws java.net.MalformedURLException
     */
    public Resultado(String mensagem) throws MalformedURLException, IOException {
        initComponents();
        
        this.mensagem = mensagem;
        
        String[] parts = mensagem.split("\n");
        String prato = parts[0]; 
        String regiao = parts[2];
        String regimeAlimentar = parts[4];
        String tipoComida = parts[6];
        String preco = parts[8];
        String ocasiao = parts[10];
        String foto = parts[12];
        String descricao = parts[14];
        
        
        URL url = new URL(foto);
        BufferedImage image = ImageIO.read(url);
        System.out.println("Load image into frame...");
        lbFoto.setIcon(new ImageIcon(image.getScaledInstance(200, 200, BufferedImage.TYPE_INT_ARGB)));
        
        lbPrato.setText(prato);
        lbRegiao.setText(regiao);
        lbRegime.setText(regimeAlimentar);
        lbTipo.setText(tipoComida);
        lbPreco.setText(preco);
        lbOcasiao.setText(ocasiao);
        
         //permite fazer quebra de linha
        txtDescricao.setLineWrap( true );
        txtDescricao.setText(descricao);
       
         
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbPrato = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbRegiao = new javax.swing.JLabel();
        lbRegime = new javax.swing.JLabel();
        lbTipo = new javax.swing.JLabel();
        lbPreco = new javax.swing.JLabel();
        lbOcasiao = new javax.swing.JLabel();
        lbFoto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(552, 419));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(552, 419));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(135, 92, 0, 0);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(626, 500));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(626, 500));
        jPanel2.setLayout(null);

        lbPrato.setText("prato");
        jPanel2.add(lbPrato);
        lbPrato.setBounds(30, 40, 170, 25);
        jPanel2.add(jLabel2);
        jLabel2.setBounds(105, 106, 0, 0);

        lbRegiao.setText("regiao");
        jPanel2.add(lbRegiao);
        lbRegiao.setBounds(30, 80, 160, 30);

        lbRegime.setText("regimeAlimentar");
        jPanel2.add(lbRegime);
        lbRegime.setBounds(30, 130, 180, 28);

        lbTipo.setText("tipoComida");
        jPanel2.add(lbTipo);
        lbTipo.setBounds(30, 180, 130, 24);

        lbPreco.setText("preco");
        jPanel2.add(lbPreco);
        lbPreco.setBounds(30, 220, 90, 30);

        lbOcasiao.setText("ocasiao");
        jPanel2.add(lbOcasiao);
        lbOcasiao.setBounds(30, 270, 130, 30);
        jPanel2.add(lbFoto);
        lbFoto.setBounds(250, 40, 250, 230);

        txtDescricao.setEditable(false);
        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 310, 520, 96);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 560, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main1(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Teste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbFoto;
    private javax.swing.JLabel lbOcasiao;
    private javax.swing.JLabel lbPrato;
    private javax.swing.JLabel lbPreco;
    private javax.swing.JLabel lbRegiao;
    private javax.swing.JLabel lbRegime;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JTextArea txtDescricao;
    // End of variables declaration//GEN-END:variables
}
